export enum Path {
  Profection = 'profection',
  MedievalProfection = 'medieval_profection',
  CustomDayProfection = 'custom_day_profection',
  Transit = 'transit',
  Firdaria = 'firdaria',
  SolarReturn = 'return/solar',
  LunarReturn = 'return/lunar',
  DailyReturn = 'return/daily',
  SolarcomparNative = 'return/solar_native',
  NativecomparSolar = 'return/native_solar',
  LunarcomparNative = 'return/lunar_native',
  NativecomparLunar = 'return/native_lunar',
  DailycomparNative = 'return/daily_native',
  NativecomparDaily = 'return/native_daily',

  Direction = 'direction',
  DailyDirection = 'daily_direction',
  SolarArc = 'solar_arc',
  QuadrantProcess = 'quadrant_process',
}
